### PR TITLE
Update controller.ts

### PR DESCRIPTION
**Pull request by PopescuIon**

### CODE REVIEW

**Comment by jeffijoe** [comment]
Hi @PopescuIon, could you provide some context for the requested change?

**Comment by PopescuIon** [comment]
Because when I try to use the awilix-express library I get these errors
Namespace '"/node_modules/glob/dist/commonjs/index"' has no exported member
'IOptions'.
I've been reading up on glob modules and noticed that it returns the
GlobOptions interface and not IOptions
I made these modifications locally and it works ok but I have problems when
I publish to the server

În mar., 9 ian. 2024 la 11:40, Jeff Hansen ***@***.***> a
scris:

**Comment by jeffijoe** [comment]
That is weird, I've updated all dependencies locally and it's still `IOptions` for me.

**Comment by jeffijoe** [comment]
I released a new version, please check and see if that is still causing issues. If not, please rebase this PR so it runs the CI, I just migrated to GHA.

**Pull request closed without merging**
